### PR TITLE
Bumping static version to 1.5.0

### PR DESCRIPTION
**Pull request by shlevy**
This way packages needing recent changes from git can set their version bounds appropriately and be ready for the next release.

### CODE REVIEW

**Comment by shlevy** [comment]
@brendanhay

**Comment by shlevy** [comment]
Not sure how to update the versions of generated packages.

**Comment by brendanhay** [comment]
I'm not sure I understand the initial premise - I assume you'll be pinning to a specific git commit anyway? The release will be developed in an independent feature branch(es), so you'd still be better off having the upper bound set to `< 1.5`.

**Comment by shlevy** [comment]
The idea is to have a bound that will work now *and* when the next release comes out. A bound of `>=1.4.5` doesn't really work now because `1.4.5` doesn't have stuff I need, I just happen to be completely in control of which "1.4.5" I'm using so it's fine.

Not a huge deal, of course. Just a slight convenience.

**Pull request closed without merging**
