### PR TITLE
Implement instance MonadUnliftIO (AWST' r m) in terms of withRunInIO

### PR DESCRIPTION
**Pull request by akrmn**
Moved implementation of instance behind CPP conditionals to check version of `unliftio-core`.

### CODE REVIEW

**Comment by akrmn** [comment]
This PR is like #562 from @cfraz89 or #563 from me, but the CPP conditionals should get the repo to build on any version of `unliftio-core`.

**Comment by brendanhay** [comment]
Thanks for the PR @akrmn - can you take a look at the conflicts and modify if applicable?

**Comment by akrmn** [comment]
Hey! I've rebased now. It seems that there was a similar commit some time after I opened the PR, but I think the `INLINE` pragmas and the simpler implementation of `withRunInIO` are still worth considering. Behaviour should be the same, with a bit less wrapping/unwrapping.

**Comment by akrmn** [comment]
Thanks for merging this one!

**Pull request merged**
