### PR TITLE
Release 1.7.0

### LINKED ISSUE #574: New hackage release
It has been a year and many commits since the last release. It would be good for a new release version to be uploaded to Hackage especially now that there is GHC 8.10 and issues like #546 have been fixed.

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #574

### CODE REVIEW

**Comment by rossabaker** [comment]
Still need to refresh the generated code and bump the versions.

I'm proposing we call it 1.7.0, but am new here and would bend easily to stronger opinions.

**Comment by brendanhay** [comment]
`1.7.0` makes sense. We're at the point where we have that many changes since the last release I'm going to assume there's a non-zero possibility of breakage.

**Comment by TomMD** [comment]
Anything I can do to help get this moving?

**Comment by turboMaCk** [comment]
Is there anything we can do to help unblock this?

**Comment by domenkozar** [comment]
@MichaelXavier :pray:

**Comment by endgame** [comment]
Looks like we're going towards [2.0](https://github.com/brendanhay/amazonka/pull/617#issuecomment-830606997), so I'm not sure if this remains relevant. @brendanhay may be able to pull the changelog changes, but after that it might make sense to close this PR.

**Pull request closed without merging**
