### PR TITLE
Ghc 98 gen

### PR DESCRIPTION
**Pull request by endgame**

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Hey @brendanhay! Kindly reminder to merge and release this.

**Comment by brendanhay** [comment]
Anything else needed here @endgame?

**Comment by endgame** [comment]
I've been keeping this open to remind myself to do the mass-revision of existing releases before this goes out. Let me check if there's anything else easy that should go in the next release, since I feel like I have to justify sending 300+ packages to Hackage.

**Comment by Bodigrim** [comment]
@endgame thanks for your work! It would be great to get it released indeed.

**Comment by endgame** [comment]
I'll not delete the branch in case people are pointing to it by name (via `source-repository-package` etc)

**Pull request merged**
