### PR TITLE
Close connections immediately (when we know that we can do that)

### LINKED ISSUE #490: Open connections are leaking
I do a bunch of `SQS.deleteMessage`s in a loop, and experience long waits (5-10 seconds) after getting 99 open connections. This happens with https://github.com/iain/fake_sqs (I haven't tested with real SQS).

This behavior is introduced by a recent commit (made after 1.6.0 was released): https://github.com/brendanhay/amazonka/commit/2688190f659e4d87fd6862b52b04be706b17d251.

My guess is that in the absence of finalizers in conduit-1.3, nothing is closing connections open by `Response`s. The following diff fixes the behavior of `deleteMessage` for me:

```diff
diff --git a/core/src/Network/AWS/Response.hs b/core/src/Network/AWS/Response.hs
index 4791de6a3c..907b0faa05 100644
--- a/core/src/Network/AWS/Response.hs
+++ b/core/src/Network/AWS/Response.hs
@@ -45,8 +45,9 @@ receiveNull :: (MonadResource m, MonadThrow m)
             -> Proxy a
             -> ClientResponse
             -> m (Response a)
-receiveNull rs _ = stream $ \_ _ x ->
-    liftResourceT (x `connect` pure (Right rs))
+receiveNull rs _ = stream $ \_ _ x -> do
+    sinkLBS x
+    pure (Right rs)

 receiveEmpty :: (MonadResource m, MonadThrow m)
              => (Int -> ResponseHeaders -> () -> Either String (Rs a))
```

It's still slower than it used to be (I've no idea why), but at least it doesn't leak connections anymore and I get no stuck requests.

Other `receiveBlah` functions might also be affected.

### PR DESCRIPTION
**Pull request by neongreen**
Fixes #490.

I'm going to test this in https://github.com/wireapp/wire-server so please don't merge that yet. @LeifW @naushadh @dsturnbull would you also like to take a look?

### CODE REVIEW

**Comment by neongreen** [comment]
So there's a choice of two commits now:

* one does `sinkNull`
* the other closes the connections without sinking anything

The latter is several times faster in my benchmarks (five times faster for SQS's `deleteMessage` with local fake SQS), but I'm not sure it's correct. On the other hand, I also don't see any reason why it wouldn't be correct, but it still seems suspicious.

**Comment by naushadh** [comment]
I too would prefer the faster way, correctness provided. Perhaps long term we really do need some actual testing against AWS (or a mock of it) (https://github.com/brendanhay/amazonka/issues/477) and/or lift connection handling into the type system.

**Comment by neongreen** [comment]
This is in production in https://github.com/wireapp/wire-server now and things haven't broken yet, so I'm in favor of merging it. cc @MichaelXavier?

**Comment by dzhus** [comment]
Same here – *seems* ok to merge

**Comment by mheinzel** [comment]
I rebased this change, which we have been running in production in https://github.com/wireapp/wire-server for over a year at this point.

Some CI builds failed because of `happy`, one because of ["No output has been received in the last 10m0s"](https://travis-ci.org/brendanhay/amazonka/jobs/648467830), but this seems to happen on master, too.

If there is any interest in merging this, that would be great. If not, we'll keep using our fork.
Let me know if there is anything I could do to help make this happen.

**Comment by brendanhay** [comment]
LGTM

**Comment by mheinzel** [comment]
Wow, thanks for the quick response!

**Pull request merged**
