### PR TITLE
Less Free

### PR DESCRIPTION
**Pull request by brendanhay**
This is a sad PR which removes the underlying free monad due to broken intuition regarding exceptions. See #185 for more information.

### CODE REVIEW

**Comment by kim** [comment]
You should write a blog post about this

**Comment by brendanhay** [comment]
Haha. The irony - less monads for free, maybe?

**Comment by proger** [comment]
free monads have exceptional cost

**Comment by joehillen** [comment]
+1 for a blog post about this. I'd like to understand why you can't use Free here.

**Comment by brendanhay** [comment]
Nothing preventing use of `Free` other than my own errors/assumptions WRT exception semantics. I'll revisit it sometime.

**Comment by brendanhay** [comment]
Issue #185 mentioned above demonstrates the motivating example.

Briefly, due to the exception semantics around how I'd constructed the `Free` DSL + interpretation(s) causing exceptions to be thrown by `runAWS*`, not at the call site for `send/paginate/await/...`.

This caused some fairly non-intuitive (and undesired) behaviour if, for example, you'd like to use the idiom `catching _Error (send ...)`, this would type-check, but then nothing would actually be caught by `catching` and the expected error would be thrown in `IO`. (Or whatever `MonadThrow` instance `runAWS*` was run in.).

**Pull request merged**
