### PR TITLE
Use default github templates for bugs/features

### PR DESCRIPTION
**Pull request by brendanhay**

### CODE REVIEW

**Comment by brendanhay** [comment]
@endgame Rather annoyingly, you can't see how it affects the new issue UX until they're on `main`. Try going through "New Issue" since the release checklist now appears there too.

**Comment by endgame** [comment]
They look fine. I find the default GH bug/feature request templates tend not to add all that much, and would probably trim them right back and/or merge them. Up to you.

**Comment by endgame** [comment]
Release checklist looks fine though.

**Comment by brendanhay** [comment]
Feel free to tweak/merge as desired - the files are in the `.github/` directory now - just removing one of them and renaming the other should be sufficient, modulo default labels.

**Pull request merged**
