### PR TITLE
First steps toward Nix/CI

### PR DESCRIPTION
**Pull request by endgame**
#574 make it look like the lack of good build caching is a blocker for CI, which is a blocker for a release. This PR aims to take the first step in unblocking that.

It adds IOHK's `haskell.nix`, with pinning managed by `niv`. `ci.nix` sets up `haskell.nix` projects for GHC 8.6.5, 8.8.4, and 8.10.4, testing both the corresponding `stack.yaml` and the `cabal.project`.

I've tried to avoid making code changes or version bumps, but I needed new `unexceptionalio` to get `MonadFail` support, a tighter bound on `haskell-src-exts` to get `gen` to compile, and I had to tweak a test case so that a `HashMap`'s keys were listed in the same order when using both `hashable-1.3.0.0` and `hashable-1.3.1.0` (which changed the hashing algorithm).

The nix builds work but take a long time - I've tested all three compilers, both `cabal` and `stack` variants, by building the six derivations in the result set of `ci.nix`. They do take a while to start, possibly due to evaluating the giant nix expressions generated by `haskell.nix`. If you'd like, I can try to generate individual `haskell.nix` projects for each `amazonka-*` package.

Happy to rework any or all of this if it helps - anything to get the release cadence back up.

### CODE REVIEW

**Comment by gwils** [comment]
Incredible effort!
Could you please explain your grand plan? Is the idea to use Github Actions to run a nix-based CI with delicious caching somewhere? Apologies if you've outlined this elsewhere.

**Comment by endgame** [comment]
@brendanhay was [talking about using cachix](https://github.com/brendanhay/amazonka/issues/574#issuecomment-731806416) to support CI, and moving CI off Travis and onto GH actions, so this is trying to support that. If he's happy with the use of `haskell.nix`, I'll look into getting some actions going once we know where to put the cache.

It might be necessary to split CI into separate jobs for each package in the repo; I'm not yet sure what the actual performance on an actual runner will be like.

**Comment by brendanhay** [comment]
FWIW this work was already in the main-develop branch - the haskell.nix + cachix integration is there and it looks like a single job will probably be fine, at least initially - once cachix is primed.

**Comment by endgame** [comment]
That's excellent news @brendanhay . Is there anything here you'd want me to split out or cherry-pick in a separate PR?

For the next 1.5 weeks I can justify working on amazonka during work time - where would that time be most usefully spent?

**Comment by brendanhay** [comment]
Just grab whatever you want/need from that branch, if anything - ie. the
cachix configuration. Given the first CI build will be the most painful and
will possibly timeout, once you're happy with the PR let me know so I can
build it locally and push the derivations to amazonka.cachix.org, to prime
the cache for GitHub actions.

**Comment by endgame** [comment]
I've started a new branch that build on your branch's nix setup but it's not going to be ready this side of the weekend. I intend to write a nix expression to generate the github actions code, and as part of that it'll generate a set of nix targets that you can build to prime the cache. Stay tuned.

**Comment by endgame** [comment]
I see you've got github workflows defined in main-develop too. I'll pull them in and see if they can work for current `develop`

**Pull request closed without merging**
