### PR TITLE
Amazonka s3 model update

### PR DESCRIPTION
**Pull request by domenkozar**
I've updated the S3 model because I was getting runtime errors in production due to missing INTELLIGENT_TIERING StorageClass sum type.

I've split the commits in two, while README instructs not to commit generates files, they have to be eventually generated and with this PR I can also use the fork myself.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
@domenkozar looks like there's some significant compile errors on some of the branches. Are you able to look into those?

**Comment by domenkozar** [comment]
Sorry for radio silence, I'll get back to this soon (maybe at ZuriHac)

**Comment by Fuuzetsu** [comment]
It's been quite a while and INTELLIGENT_TIERING basically can not be used with `amazonka` at all due to this missing.

**Comment by brendanhay** [comment]
There is an in progress branch with a `2.0.0.0` release being prepared that supersedes this. It also includes the changes from #597 - `INTELLIGENT_TIERING` will become a pattern synonym, which should avoid this issue in future.

**Comment by Fuuzetsu** [comment]
Great. In meantime if someone wants to take S3 changes I have a branch at https://github.com/tsurucapital/amazonka/tree/update-api for now

**Pull request closed without merging**
