### PR TITLE
Replace Network.AWS namespace with Amazonka

### LINKED ISSUE #312: [RFC] Consider renaming module namespace
This is a call for comments on a potentially contentious change, which arises only due to my intense dislike of the current `Network.AWS.` namespace due to all of the packages complete dissociation with actual networking and Java-style taxonomy in general.

> Prior ~~bike-shedding~~ discussion:
> - [What's the Right Way to Name Packages and Modules?](https://www.reddit.com/r/haskell/comments/2ggopt/whats_the_right_way_to_name_packages_and_modules/)
> - [Packages and Namespace Naming Conventions](https://www.reddit.com/r/haskell/comments/1qrilm/packages_and_namespaces_naming_convention/)
> - [Towards a Better Haskell Package](http://fvisser.nl/post/2013/may/28/towards-a-better-haskell-package.html)

Ideally since the packages are named `amazonka` and `amazonka-*`, I'd like the namespace of the modules to reflect the package name. Illustrating the potential change using `amazonka-dynamodb`:

**Current**

```
Network.AWS.DynamoDB
Network.AWS.DynamoDB.BatchGetItem
Network.AWS.DynamoDB.BatchWriteItem
Network.AWS.DynamoDB.CreateTable
Network.AWS.DynamoDB.DeleteItem
Network.AWS.DynamoDB.DeleteTable
Network.AWS.DynamoDB.DescribeLimits
Network.AWS.DynamoDB.DescribeTable
Network.AWS.DynamoDB.GetItem
Network.AWS.DynamoDB.ListTables
Network.AWS.DynamoDB.PutItem
Network.AWS.DynamoDB.Query
Network.AWS.DynamoDB.Scan
Network.AWS.DynamoDB.Types
Network.AWS.DynamoDB.UpdateItem
Network.AWS.DynamoDB.UpdateTable
Network.AWS.DynamoDB.Waiters
```

**Proposed**

```
Amazonka.DynamoDB
Amazonka.DynamoDB.BatchGetItem
Amazonka.DynamoDB.BatchWriteItem
Amazonka.DynamoDB.CreateTable
Amazonka.DynamoDB.DeleteItem
Amazonka.DynamoDB.DeleteTable
Amazonka.DynamoDB.DescribeLimits
Amazonka.DynamoDB.DescribeTable
Amazonka.DynamoDB.GetItem
Amazonka.DynamoDB.ListTables
Amazonka.DynamoDB.PutItem
Amazonka.DynamoDB.Query
Amazonka.DynamoDB.Scan
Amazonka.DynamoDB.Types
Amazonka.DynamoDB.UpdateItem
Amazonka.DynamoDB.UpdateTable
Amazonka.DynamoDB.Waiters
```

Since this would be a widespread breaking-change, additional placeholder modules would be added to preserve the old namespaces so that existing code doesn't break until a deprecation period can be served. An example of a placeholder module to ensure code importing `Network.AWS.DynamoDB` continues to work is:

```
module Network.AWS.DynamoDB (module Export) where

import Amazonka.DynamoDB as Export
```

What modules actually need this treatment? Providing placeholders for all modules would simply slow down compilation. I'd expect only the top-level `Network.AWS.*` and `Network.AWS.*.Types` would be necessary. This would result in the `exported-modules` looking as follows:

```
exported-modules:
      Network.AWS.DynamoDB
    , Network.AWS.DynamoDB.Types

    , Amazonka.DynamoDB
    ...
```

But the most important question - is this just too invasive? I'm currently leaning on the side of the pain outweighs the gain.

### PR DESCRIPTION
**Pull request by brendanhay**
Still as contentious as the day it was raised - but if there's any time to release it as part of the breaking changes, or permanently shelve it, it's now.

Closes #312

### CODE REVIEW

**Comment by endgame** [comment]
I agree that now's the time to either ship it or shelve it.

I personally liked the hierarchical namespaces as an ideal, but I think I'm in a decreasing minority. `Network.AWS` should probably have been `Cloud.AWS`, but these packages are enough of their own universes that even under hierarchical module names, they'd deserve a top-level namespace.

So I say, **ship it**.

**Comment by brendanhay** [comment]
Tangentially, I don't mind the idea of logically grouping functionality in imports by the namespace (say, `Cloud.*` for all your magic cloud related code) in theory - but having to explain to newcomers constantly that `Network.AWS` is in the `amazonka` package is the larger annoyance, in my own experience. `Amazonka` is from the `amazonka` package, `Dhall` is from the `dhall` package, etc.

Some outstanding CI issues from a personal GCP account apocalypse yesterday - I'll resolve those and get the cached updated before merging.

**Comment by ketzacoatl** [comment]
:+1: on this being more intuitive/obvious/consistent with other packages.

**Comment by endgame** [comment]
Can you please update the "major changes" section of the changelog before merging?

**Comment by brendanhay** [comment]
Jawohl

**Comment by endgame** [comment]
Looks good to me.

**Pull request merged**
