### PR TITLE
Colons in error headers

### LINKED ISSUE #808: Cannot catch with IoT._ResourceNotFoundException
I use amazonka-iot from amazonka-2.0.0-rc1 (commit 0ccede621e56fb6f240e4850e205cde82d0e4a4b).

I ran something like the expression below.

```haskell
import           Amazonka             (trying)
import qualified Amazonka
import qualified Amazonka.IoT as IoT

runResourceT $ trying IoT._ResourceNotFoundException $ Amazonka.send env $ IoT.newDescribeThing "not-present"
```

The expectation was that "not-present" Thing did not exist, so the `ResourceNotFoundException` was thrown, caught and converted to `Left`.
However, the exception was not caught. It's like

```
 ServiceError (ServiceError'
  { _serviceErrorAbbrev = Abbrev {fromAbbrev = "IoT"}
  , _serviceErrorStatus = Status {statusCode = 404, statusMessage = "Not Found"}
  , _serviceErrorHeaders = [("Date","Thu, 25 Aug 2022 07:09:51 GMT"),("Content-Type","application/json"),("Content-Length","59"),("Connection","keep-alive"),("x-amzn-RequestId","ec64939b-52c3-403d-9ef8-3a83f8b82ccf"),("x-amzn-ErrorType","ResourceNotFoundException:http://iot.amazonaws.com/doc/2015-10-02/")]
  , _serviceErrorCode = ErrorCode "ResourceNotFoundException:http://iot.amazonaws.com/doc/2015-10-02/"
  , _serviceErrorMessage = Just (ErrorMessage {fromErrorMessage = "Thing XXXXXXXXX not found."})
  , _serviceErrorRequestId = Just (RequestId {fromRequestId = "ec64939b-52c3-403d-9ef8-3a83f8b82ccf"})
  })
```

I suspect that the `_ResourceNotFoundException` could not match `_serviceErrorCode = ErrorCode "ResourceNotFoundException:http://iot.amazonaws.com/doc/2015-10-02/"`.

### PR DESCRIPTION
**Pull request by endgame**
Fixes #808

### CODE REVIEW

**Comment by endgame** [comment]
@debug-ito: Can you please test whether this works for you? It looked good to me in a REPL.

**Comment by debug-ito** [comment]
Thanks. I'll try it.

**Comment by debug-ito** [comment]
I'm testing this branch, but the compiler complains that there is no `FromKeys` data constructor in Amazonka module. However, it's described in this document https://amazonka.brendanhay.nz/docs/libZSamazonkaZSamazonka/Amazonka.html#t:Credentials

Is there any up-to-date online documents on amazonka API?

**Comment by endgame** [comment]
Unfortunately the CI job which updates that documentation site is broken, something to do with credentials. Only @brendanhay can fix that.

A [migration guide for the authentication subsystem](https://github.com/brendanhay/amazonka/blob/main/lib/amazonka/CHANGELOG.md#major-changes) is in `amazonka`'s `CHANGELOG.md`, and you can see the auth modules in [`lib/amazonka/src/Amazonka/Auth/`](https://github.com/brendanhay/amazonka/tree/641c8e32db4a5ff259474128a810b5b6264cb1b1/lib/amazonka/src/Amazonka/Auth). The relevant parts are re-exported from module `Amazonka.Auth`.

**Comment by debug-ito** [comment]
Thanks! The migration guide is very helpful.

**Comment by debug-ito** [comment]
I used `IoT._ResourceNotFoundException` and it successfully caught the exception. #808 is fixed.

**Pull request merged**
