### PR TITLE
Ci take two

### PR DESCRIPTION
**Pull request by endgame**
This branch cherry-picks the build fixes from #611 and backports the nix/CI framework found on `main-develop`. I've tested that it successfully builds using the following commands:

* `nix-build -A workflows.core --argstr ghc884`
* `nix-build -A workflows.libs --argstr ghc884`
* `nix-build -A workflows.core --argstr ghc8104`
* `nix-build -A workflows.libs --argstr ghc8104`

I had to make some fixes to the nix framework:

* The `nixpkgs` passed to `haskell.nix` is provided by the `haskell.nix` framework. This increases the cache hit rate if you have IOHK's cache set up, and avoids building at least one copy of GHC.
* The `predicate` function passed into the nix local libs wasn't doing anything. Now `workflows.core` and `workflows.libs` are split correctly.
* I updated all the nix pins to get GHC 8.10.4.

I didn't bother testing all of {stack,cabal} with GHC {8.6.5,8.8.4,8.10.4}. I figured that if you're happy with the build matrix on `main-develop`, then so am i.

I'll cherry pick these fixed onto another branch so they can go back into `main-develop`.

cc @domenkozar @robertfischer in case they want to weigh in.

Closes #611 .

### CODE REVIEW

**Comment by brendanhay** [comment]
Looks good! The cache is now updated for `linux-x86_64`, I'm still waiting on the `darwin-x86_64` builder to finish but once that's done I'll trigger the workflow run via merge.

**Comment by RobertFischer** [comment]
SO HAPPY

**Comment by RobertFischer** [comment]
This is a (the?) major step towards #574, too, so I'm pinging it.

**Comment by endgame** [comment]
Hi @brendanhay , how'd you go with the darwin builder? Is there any assistance I can provide here?

**Comment by brendanhay** [comment]
@endgame The Darwin build is fine, somewhat ironically, the Linux builds are [failing](https://github.com/brendanhay/amazonka/runs/2269974911) due to errors like the following:

```
# Logs
2021-04-05T13:28:48.6584471Z preallocating file of 27122 bytes: No space left on device

# Dashboard
You are running out of disk space. The runner will stop working when the machine runs out of disk space.
Free space left: 0 MB
```

The Darwin runner is in GitHub's own datacenter, but the Linux runners are just smol Azure DS2v2 instances with 14GiB (total) disk space:

image

The `ubuntu-latest` image which contains things like .NET core only gives you roughly 10GiB of free space to work with.

I haven't investigated further but it seems reasonable that Ubuntu + Nix + Cachix + realising the entire set of build derivations is over well over 10GiB. Unless someone has another idea, to try and work around this I'll split the job into 2 separate sequential workflows initially, doing a set of core libraries + cachix push, then the remaining set of actual API libraries in the second step to see if that's sufficient to get under the limit.

**Comment by domenkozar** [comment]
That can happen when building lots of Haskell packages.

I suggest adding `    - run: sudo rm -rf /opt&` step to free up some space.

**Comment by endgame** [comment]
I don't have a good feeling about that "split the build" idea, because nix doesn't even download GHC before it gets `ENOSPC`'d. Can you stick a `df -h` at the start and end of the mac run, and at the start of the linux run? That'll give us a good sense of how much space in which we have to work.

I found https://github.com/easimon/maximize-build-space , which does some ugly things with LVM to scrounge up more space. That action also has optional parameters to remove stuff like the .NET runtime, which you could crib before adopting such extreme measures.

**Comment by endgame** [comment]
@brendanhay if you can generate a temporary read-only token for amazonka cachix, I will try and get CI working in my fork this weekend, and update the PR.

**Comment by endgame** [comment]
@brendanhay belay that. I'm priming my own cachix to muck around with.

**Comment by endgame** [comment]
`- run: sudo rm -rf /opt` allows the build to succeed, see https://github.com/endgame/amazonka/runs/2310419762 . However, there's only about 2.5G free on `/` after the build finishes, and that's with every derivation a cache hit. I will experiment some with https://github.com/easimon/maximize-build-space and report back.

**Comment by endgame** [comment]
@brendanhay These are the changes I think should happen on your CI branch:

1. `- run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt&` runs in the background and removes ~42GB of crap. That should be more than enough, and avoids crazy LVM shenanigans.
2. Use this version of the `install-nix-action`, so you can pull from IOHK hydra:
   ```
   - uses: cachix/install-nix-action@v12
     with:
       extra_nix_config: |
         trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
         substituters = https://hydra.iohk.io https://cache.nixos.org/
   ```
3. If you get OOMs building `amazonka-ec2` or whatever, consider creating another/larger swapfile on `/mnt`.

You can use the `maximize-build-space` action to create a ~60GB `/nix`, but that seems brittle if you need space anywhere else in the system.

**Comment by endgame** [comment]
I am now seeing timeouts from `hydra.iohk.io` on some of my test actions. Given that you've fully primed the caches, all the stuff you need from there should be in your cachix. Maybe it's better not to add their cache to the `extra_nix_config`?

**Comment by endgame** [comment]
@brendanhay Thinking about closing this PR, since branch `bh/ci` has diverged significantly. Any reason I should keep it open? Also: anything else I can help with?

**Pull request closed without merging**
