### PR TITLE
Add config files for apigatewaymanagementapi

### PR DESCRIPTION
**Pull request by pparkkin**
The documentation is a little unclear on how exactly a new API should be included. This is my attempt at adding the `apigatewaymanagementapi`.

I got the model files from botocore, and created the other two files myself.

Everything compiles on my laptop. I wasn't sure how to run tests, but will be happy to run test if provided instructions on how to do so.

### CODE REVIEW

**Comment by pparkkin** [comment]
All the failing builds are 7.10.3 and 8.0.2 builds, and they fail with the following error.
```
happy           > Linking /tmp/stack23357/happy-1.19.5/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup ...
happy           > Configuring happy-1.19.5...
happy           > build
happy           > Building happy-1.19.5...
happy           > Preprocessing executable 'happy' for happy-1.19.5...
happy           > setup: The program 'happy' is required but it could not be found
--  While building package happy-1.19.5 using:
      /tmp/stack23357/happy-1.19.5/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build --ghc-options ""
    Process exited with code: ExitFailure 1
The command "./script/travis-build" exited with 1.
```
Any ideas what might be causing it, or what I can do to fix it?

**Comment by LeifW** [comment]
Looks like we need the `happy` executable on Travis wherever the build is running?

**Comment by pparkkin** [comment]
Looks like possibly an issue with Travis. The build ran successfully when Travis ran it for the branch. 

Is there any way to rerun it?

**Comment by pparkkin** [comment]
Is there something I can do to help get this merged?

**Comment by brendanhay** [comment]
:+1:

**Pull request merged**
