### PR TITLE
lambda model update

### PR DESCRIPTION
**Pull request by nhibberd**
cc @mgajda

### CODE REVIEW

**Comment by kahlil29** [comment]
Hey! Any idea when this can be merged? Or what is blocking merging, if anything?

**Comment by nhibberd** [comment]
> Hey! Any idea when this can be merged? Or what is blocking merging, if anything?

The tests that were failing looked like flakey CI, the `lambda` build is green

**Comment by nhibberd** [comment]
Thoughts @brendanhay ?

**Comment by utdemir** [comment]
Hey. It looks like Lambda models have updated again, and the new ones comes with `PutFunctionEventInvokeConfig` resource that I need. Any chance this PR can be updated with the new models, since creating a new one feels a bit odd when this is also open?

**Comment by K0Te** [comment]
Hi,
There are new python runtimes in lambda - this PR includes `python3.6`, but now AWS also provide `python3.7`.
Furthermore, currently available `python3.5` runtime is not supported for edge lambdas anymore, so current  it's impossible to create edge lambda with current `amazonka` version.

Can I somehow help to get this PR updated/merged ?

**Comment by brendanhay** [comment]
`develop` and `main` now contain code generated from the latest Lambda service description.

**Pull request closed without merging**
