### PR TITLE
Fix the svcPrefix for the applicationAutoScaling Service

### LINKED ISSUE #539: Requests sent to Application Autoscaling are not properly signed
When running the following, I'm getting this exception:

```haskell
runResourceT . runAWS env . send $ describeScalableTargets Dynamodb
```
```haskell
*** Exception: ServiceError'
  { _serviceAbbrev = Abbrev "ApplicationAutoScaling"
  , _serviceStatus =
      Status { statusCode = 400 , statusMessage = "Bad Request" }
  , _serviceHeaders =
      [ ( "x-amzn-RequestId" , "<REMOVED>" )
      , ( "Content-Type" , "application/x-amz-json-1.1" )
      , ( "Content-Length" , "126" )
      , ( "Date" , "Tue, 30 Jul 2019 06:30:55 GMT" )
      , ( "Connection" , "close" )
      ]
  , _serviceCode = ErrorCode "InvalidSignature"
  , _serviceMessage =
      Just
        (ErrorMessage
           "Credential should be scoped to correct service: 'application-autoscaling'. ")
  , _serviceRequestId =
      Just (RequestId "<REMOVED>")
  }
```

I wonder if it's maybe related to this bug in the Go SDK: https://github.com/aws/aws-sdk-go-v2/issues/163

### PR DESCRIPTION
**Pull request by axman6**
Fixes #539

### CODE REVIEW

**Comment by axman6** [comment]
Looking around this is probably not the correct way to fix this, but I can't figure out from `gen` how it should be configured to do the right thing. Any help would be greatly appreciated.

**Comment by axman6** [comment]
It looks like the real bug here is that `metadata.signingName` in the service description is being ignored completely in the code; this feels like a bad thing...

**Comment by mgajda** [comment]
Please note that your patch applies to _automatically generated_ part of the code.
So the proper way would be to either add special case to generator in `gen/src/` or fix source files in `gen/model/`(note that for the latter, repo contains only a copy of upstream files that should be fixed.)

It may also be incomplete - this service prefix is mentioned in three different files:
```sh
$ grep autoscaling 
amazonka-application-autoscaling/gen/Network/AWS/ApplicationAutoScaling/Types.hs:    , _svcPrefix = "autoscaling"
amazonka-autoscaling/gen/Network/AWS/AutoScaling/Types.hs:    , _svcPrefix = "autoscaling"
amazonka-autoscaling-plans/gen/Network/AWS/AutoScalingPlans/Types.hs:    , _svcPrefix = "autoscaling"
```

**Comment by mgajda** [comment]
Quick search reveals other services that may be affected by ignoring `signingName`:
```sh
$ egrep -r 'endpointPrefix|signingName\ gen/model/
gen/model/iot-jobs-data/2017-09-29/service-2.json:    "endpointPrefix":"data.jobs.iot",
gen/model/iot-jobs-data/2017-09-29/service-2.json:    "signingName":"iot-jobs-data",
gen/model/mediastore-data/2017-09-01/service-2.json:    "endpointPrefix":"data.mediastore",
gen/model/mediastore-data/2017-09-01/service-2.json:    "signingName":"mediastore",
gen/model/meteringmarketplace/2016-01-14/service-2.json:    "endpointPrefix":"metering.marketplace",
gen/model/meteringmarketplace/2016-01-14/service-2.json:    "signingName":"aws-marketplace",

gen/model/lex-runtime/2016-11-28/service-2.json:    "endpointPrefix":"runtime.lex",
gen/model/lex-runtime/2016-11-28/service-2.json:    "signingName":"lex",
gen/model/ses/2010-12-01/service-2.json:    "endpointPrefix":"email",
gen/model/ses/2010-12-01/service-2.json:    "signingName":"ses
gen/model/pricing/2017-10-15/service-2.json:    "endpointPrefix":"api.pricing",
gen/model/pricing/2017-10-15/service-2.json:    "signingName":"pricing",
gen/model/iot-data/2015-05-28/service-2.json:    "endpointPrefix":"data.iot",
gen/model/iot-data/2015-05-28/service-2.json:    "signingName":"iotdata"
gen/model/cloudhsmv2/2017-04-28/service-2.json:    "endpointPrefix":"cloudhsmv2",
gen/model/cloudhsmv2/2017-04-28/service-2.json:    "signingName":"cloudhsm",
gen/model/appstream/2016-12-01/service-2.json:    "endpointPrefix":"appstream2",
gen/model/appstream/2016-12-01/service-2.json:    "signingName":"appstream",
gen/model/cloudsearchdomain/2013-01-01/service-2.json:    "endpointPrefix":"cloudsearchdomain",
gen/model/cloudsearchdomain/2013-01-01/service-2.json:    "signingName":"cloudsearch",
gen/model/autoscaling-plans/2018-01-06/service-2.json:    "endpointPrefix":"autoscaling",
gen/model/autoscaling-plans/2018-01-06/service-2.json:    "signingName":"autoscaling-plans",
gen/model/pinpoint/2016-12-01/service-2.json:    "endpointPrefix" : "pinpoint",
gen/model/pinpoint/2016-12-01/service-2.json:    "signingName" : "mobiletargeting"
gen/model/iot/2015-05-28/service-2.json:    "endpointPrefix":"iot",
gen/model/iot/2015-05-28/service-2.json:    "signingName":"execute-api",
gen/model/mobile/2017-07-01/service-2.json:    "endpointPrefix":"mobile",
gen/model/mobile/2017-07-01/service-2.json:    "signingName":"AWSMobileHubService",
gen/model/marketplace-entitlement/2017-01-11/service-2.json: "endpointPrefix":"entitlement.marketplace",
gen/model/marketplace-entitlement/2017-01-11/service-2.json:    "signingName":"aws-marketplace",
gen/model/lex-models/2017-04-19/service-2.json:    "endpointPrefix":"models.lex",
gen/model/lex-models/2017-04-19/service-2.json:    "signingName":"lex",
gen/model/sagemaker-runtime/2017-05-13/service-2.json:    "endpointPrefix":"runtime.sagemaker",
gen/model/sagemaker-runtime/2017-05-13/service-2.json:    "signingName":"sagemaker",
```

**Comment by mgajda** [comment]
My advice would be:
1. Add `_svcSigningName` field to `Service` record. It should default to copying `endpointPrefix` when `signingName` is not defined.
```sh
$ egrep -r _endpointPrefix gen/src
gen/src/Gen/Types/Service.hs:    , _endpointPrefix   :: Text
gen/src/Gen/Types/Service.hs:        <*> o .:  "endpointPrefix"
gen/src/Gen/Tree.hs:                , "endpointPrefix" .= (l ^. endpointPrefix)
gen/src/Gen/AST/Data/Syntax.hs:            , field (unqual "_svcPrefix")   (m ^. endpointPrefix . to str)
```
2. Update `Network.AWS.Sign.V4.Base` to use `_svcSigningName` instead of `_svgEndpoint`:
```
$ egrep -i -r _svcPrefix core/src/
core/src/Network/AWS/Types.hs:    , _svcPrefix   :: !ByteString
core/src/Network/AWS/Sign/V4/Base.hs:    , toBS (_svcPrefix     s)
core/src/Network/AWS/Endpoint.hs:defaultEndpoint (_svcPrefix -> p) r = go (CI.mk p)
```

Does this recipe look easy to follow?

**Comment by brendanhay** [comment]
I'll see if I can work through @mgajda's recommendation as that seems to be the correct fix, rather than committing a change directly to the generated code. I'll leave this PR open until another containing the `_svcSigningName` addition supersedes it.

**Comment by axman6** [comment]
Thanks Brendan, that's definitely the right fix. I guess this PR is unintentionally invoking Cunningham's law 😅

**Pull request closed without merging**
