### PR TITLE
Model update 20190324

### PR DESCRIPTION
**Pull request by nhibberd**
So I haven't tried to compile this yet :man_shrugging:

Few things of note:
- https://github.com/brendanhay/amazonka/commit/7c755337e52b3ce4b2beb676a44e686201713e0d ~ _haven't validated the impact of this yet_
- https://github.com/brendanhay/amazonka/commit/a06c75c9df50d487f5d67d7bcac55a48e27e1718
- Everything else is just `make all` + commits

I can squash the model/generation commits down if you like @brendanhay?

Overall process was fairly smooth, will try and push some documentation up in the following weeks.
Services that I couldn't upgrade (errors during generation - haven't spent anytime looking into these yet):
- `glue`
- `iot`
- `medialive`
- `mediapackage`

New services (models) that I did not generate as part of this:
- `amplify`
- `apigatewaymanagementapi`
- `apigatewayv2`
- `appmesh`
- `backup`
- `chime`
- `comprehendmedical`
- `datasync`
- `dlm`
- `docdb`
- `eks`
- `endpoints.json`
- `fsx`
- `globalaccelerator`
- `iot1click-devices`
- `iot1click-projects`
- `kafka`
- `kinesisanalyticsv2`
- `license-manager`
- `macie`
- `mediaconnect`
- `mediatailor`
- `neptune`
- `pi`
- `pinpoint-email`
- `pinpoint-sms-voice`
- `quicksight`
- `ram`
- `rds-data`
- `robomaker`
- `route53resolver`
- `s3control`
- `securityhub`
- `signer`
- `sms-voice`
- `textract`
- `transfer`
- `worklink`

### CODE REVIEW

**Comment by MichaelXavier** [comment]
I personally don't care too much about squashed commits, though I'd let Brendan weigh in as the ultimate authority if he cares to. Looks like we have a few substantive failures in the travis build.

**Comment by domenkozar** [comment]
Note, according to `gen/README` you shouldn't include generated files.

**Comment by domenkozar** [comment]
@nhibberd what's the purpose of https://github.com/brendanhay/amazonka/commit/7c755337e52b3ce4b2beb676a44e686201713e0d

**Comment by domenkozar** [comment]
Ah https://github.com/brendanhay/amazonka/issues/521

**Comment by domenkozar** [comment]
I've made a few README fixes in https://github.com/brendanhay/amazonka/pull/528

**Comment by MichaelXavier** [comment]
@nhibberd Are you going to have a chance to move forward with the remaining blocking services? It seems like the package is really falling behind so we should try to tee up a release soon.

**Comment by mgajda** [comment]
I tried to build `gen/` in this branch by `git checkout topic/model-update-20190324; cd gen; make` but I got an error message from `amazonka-gen`, about `No valid model versions found in [FilePath ...]`.

Any hints how to fix that? (I get the same error message on the `master` and `develop` branches.)

**Comment by nhibberd** [comment]
Replied offline but adding here for posterity:

----------

So it looks like these are all new services that haven't been generated before and the fix would be to add generator configs for each of them:

- https://github.com/brendanhay/amazonka/tree/develop/gen/config

Only the minimum part of the config is required, `libraryName` in this case.

Where most of these conclusions have come from:
  - [Required config file](https://github.com/brendanhay/amazonka/blob/develop/gen/src/Main.hs#L194)
  - [Config file parser](https://github.com/brendanhay/amazonka/blob/develop/gen/src/Gen/Types/Config.hs#L148)


I remember looking into this in the past at some point and I believe the conclusion was that these (config files) were still required, but I don't recall why exactly :)

**Comment by pparkkin** [comment]
What's the status of this PR?

I'm specifially interested in `apigatewaymanagementapi`.

Is there anything I can do to help move this forward?

**Comment by domenkozar** [comment]
This needs to be rebased on top of master and tests fixed.

**Comment by brendanhay** [comment]
FWIW the config files are required for no other reason than to signal that generation is opt-in. Generally new services don't always work out of the box, so we adding a configuration file acts as a gating mechanism.

**Comment by brendanhay** [comment]
All changes and updated/regenerated services are now available in `develop`.

**Pull request closed without merging**
