### PR TITLE
amazonka: Build against monad-control >=1

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by brendanhay** [comment]
So this is a slightly contentious one, which relates to issue #40. I personally have problems regarding my companies internal dependencies not supporting `>= 1`.

I'd like to know if this is isolated - or if this risks breakage for others? In which case some conditionals/CPP might be the only option.

Opinion?

**Comment by shlevy** [comment]
Not completely sure I understand the question. I'm pretty sure that anything that depends on `amazonka` after this is merged in will not be able to depend on `monad-control` `<1`, so if we need to support both of those then CPP seems like the only option.

Should I go ahead with a conditional version of this patch then?

**Comment by brendanhay** [comment]
Yes, exactly. I'm not in a position to upgrade currently hence the open ticket.

If you'd like to go ahead and add a conditional version that would be much appreciated.

**Comment by brendanhay** [comment]
On second thoughts just bumping the version according to the PVP should be sufficient.

**Comment by shlevy** [comment]
OK, pushed a version bump commit.

**Comment by brendanhay** [comment]
The `*.cabal` file versions outside of `amazonka/amazonka.cabal`, `amazonka/amazonka-gen.cabal` and `core/amazonka-core.cabal` are controlled via `gen/src/Types.hs`. You can see an example version bump commit here: https://github.com/brendanhay/amazonka/commit/b91e638a09ee656d041acac0932162c7711c63cb

That version is then rendered into all the example and library cabal files.

**Comment by shlevy** [comment]
Force-pushed a new version bump

**Comment by brendanhay** [comment]
Thanks

**Pull request merged**
