### PR TITLE
Retry 0.7

### PR DESCRIPTION
**Pull request by MichaelXavier**
So the retry library just released a breaking version change 0.7. It is up on hackage right now and I assume that means it will be updated in the stackage nightlies soon. In this PR I just bumped the minimum dependency to 0.7 and made the necessary changes. As you can see from the code, there would have been quite a bit of messy CPP to support older versions of retry. We'll be using our fork in the mean time. I'm not sure what the appropriate path forward is with stackage. Let me know if you need anything from me on this PR.

### CODE REVIEW

**Comment by brendanhay** [comment]
Thanks @MichaelXavier, can you bump the stackage resolver in `stack-7.10.2.yaml` on your branch so the Travis build can proceed? `stack-7.8.4.yaml` will probably need `retry-0.7` added to the `extra-deps` section, since the resolver is intentionally old to pick up that specific GHC version.

**Comment by MichaelXavier** [comment]
@brendanhay It looks like the last nightly didn't pick it up yet so I just set both to have extra-deps for now.  We'll see if travis takes it.

**Comment by brendanhay** [comment]
:+1:

**Comment by MichaelXavier** [comment]
Looks like that passed! Let me know if you need anything else.

**Comment by brendanhay** [comment]
Alles wunderbar, thanks!

**Pull request merged**
